### ISSUE TITLE
Can't connect mongoDB 3.0 using new auth method

### ISSUE THREAD

**Issue by phoenix1984** [afharo/mongo-stream#1]
it shows "MongoError: auth failed ...".
but I am able to connect when i use mongo-oplog module version 0.2.0

**Comment by afharo** [comment]
@phoenix1984 New version (0.1.5) should now work. It's using 1.0.0-rc-1 version of mongo-oplog.
Could you please confirm it?

**Comment by phoenix1984** [comment]
can connect to mongo 3.0 now
